name: Discord Push Notifications

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord notification
        uses: actions/github-script@v6
        with:
          script: |
            const webhookUrl = '${{ secrets.DISCORD_WEBHOOK }}';
            const repo = context.repo.repo;
            const sha = context.sha;
            const ref = context.ref;
            const actor = context.actor;
            const baseUrl = `https://github.com`; // Explicitly define the base URL
            const commitUrl = `${baseUrl}/${repo}/commit/${sha}`;
            const message = `New push to repository: ${repo}\nBranch: ${ref}\nCommit: ${sha}\nAuthor: ${actor}\nLink: ${commitUrl}`;

            const response = await fetch(webhookUrl, {
              method: 'POST',
              headers: {
                'Content-Type': 'application/json'
              },
              body: JSON.stringify({ content: message })
            });
            if (!response.ok) {
              throw new Error(`Discord webhook request failed: ${response.status} ${response.statusText}`);
            }
